Features/cas 12409 add css for cards zone
InesSimonica/react-game-cards pull request #5
Opened 2022-12-19 08:29 UTC by InesSimonica

Created a functional recently played zone and added css to it

2022-12-19 10:47 UTC, botondfd requested changes

2022-12-19 10:47 UTC, botondfd commented on src/Components/card/Card.js
> +            AddRecentCard(id)
please use camelCase while writing JS 😄

2022-12-19 10:47 UTC, botondfd commented on src/Components/homepage/Homepage.js
> +
can be removed if not used anymore

2022-12-19 10:47 UTC, botondfd commented on src/Components/homepage/Homepage.js
> +            const found = oldCardsArray.find((element) => element === cards[clickedCardId - 1])
`element === cards[clickedCardId - 1]` will this work if the cards are not ordered by `id`? 🤔 
a better solution would be:
```
const found = oldCardsArray.find((el) => el.id === clickedCardId);
```
important to know: while using array methods like `map`, `filter`, `find`, `some` you have access to the currently processed element as a whole, it is way more safe than accessing the elments by `[id]`

2022-12-19 10:47 UTC, botondfd commented on src/Components/homepage/Homepage.js
> +            }
why do we return the old elements if the clicked one is found? 🤔 
i think you can just invert the condition and omit this step

2022-12-19 10:47 UTC, botondfd commented on src/Components/homepage/Homepage.js
> +                if (oldCardsArray.length >= 4) {
why is this a special case if there are more than 4 elements?

2022-12-19 10:47 UTC, botondfd commented on src/Components/homepage/Homepage.js
> +                    oldCardsArray.pop()
please try avoiding mutating the array directly, in general it is a good practice to treat arrays as immutable and create new ones if data needs to be changed

you could try refactoring this with "non-mutating" methods, like `.filter`

more on this topic: https://www.sitepoint.com/immutable-array-methods-javascript/

2022-12-19 10:47 UTC, botondfd commented on src/Components/homepage/Homepage.js
> +                    return [...oldCardsArray]
same as above

2022-12-19 10:47 UTC, botondfd commented on src/Components/homepage/Homepage.js
> +                        AddRecentCard={addRecentCard}
`addRecentCard={addRecentCard}`
in general prop names should be camel cased

2022-12-19 11:04 UTC, ionistratifd requested changes

2022-12-19 11:04 UTC, ionistratifd commented on src/Components/Style/Recently-played-zone.css
> +}
when having the same CSS rule for numbered containers or similar stuff, you can use a class wildcard like this
```suggestion
div[class^="recently-played-cards-container-"] > .card {
  height: 206px;
  margin: 10px;
  width: 170px;
}
```
this is checking if the class attribute starts with the string you provided, so the number at the end can be dynamic

2022-12-19 11:04 UTC, ionistratifd commented on src/Components/Style/Recently-played-zone.css
> +}
the same comment applies to other instances on this CSS, you can find an explanation here: https://www.geeksforgeeks.org/wildcard-selectors-and-in-css-for-classes/

2022-12-19 11:04 UTC, ionistratifd commented on src/Components/Recently-played-zone/Recently-played-zone.js
> +                )}
you can use destructuring on cases like this, avoiding repeating every time the object name

```suggestion
                {receivedCards.map(({ id, title, url, description }) =>
                    <Card
                        key={id}
                        id={id}
                        title={title}
                        imageUrl={url}
                        description={description}
                        addRecentCard={addRecentCard}
                    />
                )}
```

2022-12-19 11:04 UTC, ionistratifd commented on src/Components/homepage/Homepage.js
> +                {cards.map((element) =>
same here with destructuring

2022-12-19 11:04 UTC, ionistratifd commented on src/Components/homepage/Homepage.js
>              console.error('[ERROR IN HOMEPAGE COMPONENT FETCH DATA]: ' + errorMessage)
i don't think this log will display the correct errorMessage, as the value of `errorMessage` is still taken from the same render, so it's not hydrated yet, this just to be checked

2022-12-20 06:57 UTC, botondfd approved these changes

2022-12-20 13:31 UTC, merged